version: '3.8'

services:
  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"                          # Modo sem banco de dados (declarativo)
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      # --- VARIÁVEIS ADICIONADAS PARA A INTERFACE GRÁFICA ---
      KONG_ADMIN_GUI_URL: http://localhost:8007     # URL onde a interface será acessada no seu navegador
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8007           # Onde o Kong vai escutar para servir a interface
    ports:
      - "8000:8000"   # Proxy público (acesso às APIs)
      - "8443:8443"   # Proxy SSL (opcional)
      - "8001:8001"   # API de administração
      - "8444:8444"   # Admin SSL
      # --- PORTA ADICIONADA PARA A INTERFACE GRÁFICA ---
      - "8007:8007"   # Interface gráfica (Kong Manager)
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro
    networks:
      - raijmobi-network

networks:
  raijmobi-network:
    external: true